exercise/urls.py
from django.urls import include, path
from django.conf.urls import url

from . import views
#from .views import geeks_view
app_name = 'exercise'
urlpatterns = [
    # ex: /exercise/
    #url(r'^exercise/timer$',views.timer, name='timer'),
    path('', views.index, name='index'),
    path('timer', views.timer, name='timer'),   
    path('timer/showtimer', views.showtimer, name='showtimer'), 
    # ex: /exercise/5/
    path('<int:question_id>/', views.detail, name='detail'),
    # ex: /exercise/5/results/
    #path('<int:question_id>/results/', views.results, name='results'),
    # ex: /exercise/5/vote/
    #path('<int:question_id>/vote/', views.vote, name='vote'),
    #path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),    
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    path('exercise/', include('exercise.urls'))
]

polls/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # ex: /polls/
    path('', views.index, name='index'),
    # ex: /polls/5/
    path('<int:question_id>/', views.detail, name='detail'),
    # ex: /polls/5/results/
    path('<int:question_id>/results/', views.results, name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

exercise/models.py
import datetime
from django.db import models
from django.utils import timezone

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text   
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)        


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text


class TotalTime(models.Model):
    totalTime = models.IntegerField()

class ExerTime(models.Model):
    # working on this - HAN
    exerid = models.AutoField(primary_key=True)
    setno = models.IntegerField()
    exert = models.IntegerField()
    breakt = models.IntegerField()
    totalt = models.IntegerField()

exercise/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from .models import Choice, Question
from django.template import loader
from django.contrib.auth.forms import AuthenticationForm
import mimetypes
from .models import ExerTime
from django.views.decorators.csrf import csrf_exempt
import time

def get_data(request):
    #Working on this - HAN
    if request.method=="POST":
        print("checkpoint")

class IndexView(generic.ListView):
    template_name = 'exercise/index.html'
    context_object_name = 'latest_question_list'
    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'exercise/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'exercise/results.html'



def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    template = loader.get_template('exercise/index.html')
    context = {
        'latest_question_list': latest_question_list,
    }
    return render(request, 'exercise/index.html', context)

def detail(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Question does not exist")
    return render(request, 'exercise/detail.html', {'question': question})

# class TimerView(generic.TimerView):
#     model = ExerTime
#     context_object_name = 'my_exer_list'
#     queryset = ExerTime.objects.all()
#     template_name = 'exercise/timer.html'

@csrf_exempt
def timer(request):

    print ("checkpoint")
    time.sleep(1)
    #exertime = get_object_or_404(ExerTime, pk=id)
    t_times = int(request.POST.get('times',0))
    t_breakt = int(request.POST.get('breakt',0))
    t_set = int(request.POST.get('set',0))
    print(type(t_times))
    t_total =0
    t_total = (t_set)*((t_breakt)-1)+(t_set)*(t_times)
    print (t_times)
    print (t_breakt)
    print (t_set)

    exertime = ExerTime(
        setno=t_set,
        exert=t_times,
        breakt=t_breakt,
        totalt=t_total
        )
    if(exertime.setno != 0) :
        exertime.save()
    #print (ExerTime.objects)
    print (ExerTime.objects.all())
    print (ExerTime.objects.all().values('exerid'))
    #tmp = ExerTime.objects.get(setno='1')
    #print(tmp)
    print (exertime)
    a = "chekc"
    print (a)
    time_hash = {"times": t_times,
            "breakt": t_breakt,
            "set": t_set,
            "a": a, }
    #exer_list = ExerTime.objects.order_by('-exerid')[:5]
    exer_list = ExerTime.objects.all()
    context = {'exer_list': exer_list}
    print (exer_list)
    #print(ExerTime.objects.all())
    #totaltime = 0
    #setno = 0
    #breakt = 0
    #exerciset = 0
    #setno = (request.POST.get('set', ''))
    #breakt = (request.POST.get('breakt', ''))
    #exerciset = (request.POST.get('times', ''))
    # if (setno == '' or breakt == '' or exerciset == '' ):
    #     totaltime = 0
    # else: 
    #     totaltime = int(setno)*(int(breakt)-1)+int(setno)*int(exerciset)
    # print (setno)
    # exertime_list =  ExerTime.objects.order_by('-setno') #WORKING ON THIS -HAN
    # print (exertime_list) #WORKING ON THIS -HAN
    # request.session['totaltime'] = totaltime
    # print (totaltime)
    # print (request.session['totaltime'])
    # #return render(request, 'exercise/timer.html')
    # time = {"totaltime": totaltime}
    # #time = {"totaltime": request.session.get('totaltime')}
    return render(request, 'exercise/timer.html', context)

def showtimer(request):
    setno = (request.POST.get('setno-anw', ''))
    breakt = (request.POST.get('break-anw', ''))
    exerciset = (request.POST.get('exercise-anw', ''))
    if (setno == '' or breakt == '' or exerciset == '' ):
        totaltime = 0
    else: 
        totaltime = int(setno)*(int(breakt)-1)+int(setno)*int(exerciset)
    time = {"totaltime": totaltime}
    #time = {"totaltime": request.session.get('totaltime')}
    return render(request, 'exercise/showtimer.html', time)



def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'exercise/results.html', {'question': question})

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'exercise/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('exercise:results', args=(question.id,)))

exercise/templates/exercise/detail.html
<form action="{% url 'exercise:vote' question.id %}" method="post">
{% csrf_token %}
<fieldset>
    <legend><h1>{{ question.question_text }}</h1></legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
</fieldset>
<input type="submit" value="Vote">
</form>

exercise/templates/exercise/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="/exercise/{{ question.id }}/">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

exercise/templates/exercise/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'exercise:detail' question.id %}">Vote again?</a>

exercise/templates/exercise/showtimer.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script type="text/javascript" src="app.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.js"></script>
  <link rel="stylesheet"href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css" />
  <link rel="stylesheet" href="hb_style.css">
</head>
<body>

  <section class="left">
    <header>
      <p>
        <a href="">ETC.</a><br>Exercise Timer Calculator
      </p>
      <div></div>
      <nav>
        <a href="/"></a>
      </nav>
    </header>
  </section>

  <section class="right">
    <h1 class="h1Title">Set <br> your <br> Timer</h1>
    <h1 class="timer disNon">
      You left <br><span style="color:red;">0</span><br> seconds!
      <script></script>
    </h1>

    <div>
      <form action="/actionpage.html">
        <label for="set">How many set <sub></sub></label>
        <input type="number" name="set" id="set" min="1" onchange="showCount('set')">

        <label for="breakt">Break time(s) <sub></sub></label>
        <input type="number" name="breakt" id="breakt" min="1" onchange="showCount('breakt')"> 

        <label for="times">Exercise time(s) <sub></sub></label>
        <input type="number" name="times" id="times" min="1" onchange="showCount('times')">

        <input type="button" id="button" value="start" onclick="starttimer()">
      </form>
    </div>
    <div class="result">
      I'm going to exercise <span id="times-span">0</span> min 
      with <span id="breakt-span">0</span> min break times 
      in <span id="set-span">0</span> set.
    </div>

  </section>
  
</body>
</html>

exercise/templates/exercise/timer.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.js"></script>
  <script src="{% static 'app.js' %}"></script>
  <link href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css" />
  <link href="{% static 'hb_style.css' %}" rel="stylesheet">
</head>

<body>

  <header>
    <p>
      <a href="">ETC.</a><br>Exercise Timer Calculator
    </p>
    <!--<nav>
      <a href="/"></a>
    </nav>-->
  </header>

  <section>
    <h1 class="title">Set <br> your <br> Timer</h1>
    
    <form action="/actionpage.html" method="POST">
    {% csrf_token %}
      
      <label for="times">Exercise time(s)</label>
      <input type="number" name="times" id="times" min="1" onchange="showCount('times')">

      <label for="breakt">Break time(s)</label>
      <input type="number" name="breakt" id="breakt" min="1" onchange="showCount('breakt')">

      <label for="set">How many set</label>
      <input type="number" name="set" id="set" min="1" onchange="showCount('set')">
      
      <input type="button" id="button" value="start" onclick="setTimer()">
    </form>
    
    <div class="result">
      I'm going to exercise <span id="times-span">0</span>s and then take <span id="breakt-span">0</span>s break times. <br>
      I will do this <span id="set-span">0</span> set.
    </div>

    <div class="test">
      <p>WORKING ON THIS-HAN</p>
      {% for exertime in exer_list %}
      <p>{{exertime.exerid}}, {{exertime.setno}}</p>
      {% endfor %}
      <p>end</p>
    </div>
    
  </section>
  
</body>
</html>